services:
- type: web
  name: cartoonize-api
  runtime: python
  buildCommand: |
    python -m venv cartoonenv
    source cartoonenv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: |
    source cartoonenv/bin/activate
    gunicorn test_code.cartoonize:app --config gunicorn.conf.py
  envVars:
  - key: PYTHON_VERSION
    value: 3.8.0
  - key: VIRTUAL_ENV
    value: cartoonenv
  - key: PORT
    value: 10000
